# Generated by Django 3.2.10 on 2021-12-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_auto_20211222_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='imagen',
            field=models.ImageField(max_length=255, null=True, upload_to='Fotosusuario/', verbose_name='Imagen'),
        ),
    ]
