# Generated by Django 3.2.10 on 2021-12-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0005_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipodocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2, verbose_name='Tipo Documento'),
        ),
    ]
