# Generated by Django 3.2.10 on 2021-12-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0006_alter_turno_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Act', 'Activo'), ('Inact', 'Inactivo'), ('Ign', 'Ignorado')], default='Ign', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipodocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=20, verbose_name='Tipo Documento'),
        ),
    ]
