# Generated by Django 3.2.10 on 2021-12-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0007_auto_20211222_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('Ign', 'Ignorado'), ('Act', 'Activo'), ('Inact', 'Inactivo')], default='Ign', max_length=20, verbose_name='Estado'),
        ),
    ]
