# Generated by Django 3.2.10 on 2021-12-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0008_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('IGN', 'Ignorado'), ('ACT', 'Activo'), ('INACT', 'Inactivo')], default='IGN', max_length=20, verbose_name='Estado'),
        ),
    ]
