# Generated by Django 3.2.10 on 2021-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0009_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='nombres',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
