# Generated by Django 3.2.10 on 2021-12-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0010_alter_turno_nombres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['id', '-documento'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
